package flashcard

import "time"

type Vocabulary struct {
	ID           int64     `db:"id"`
	Word         string    `db:"word"`
	PartOfSpeech string    `db:"part_of_speech"`
	MeaningTH    string    `db:"meaning_th"`
	Level        string    `db:"level"`
	CreatedAt    time.Time `db:"created_at"`
}

type Tag struct {
	ID        int64     `db:"id"`
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}

type VocabularyTag struct {
	VocabularyID int64 `db:"vocabulary_id"`
	TagID        int64 `db:"tag_id"`
}

type Flashcard struct {
	ID           string    `db:"id"`
	UserID       int64     `db:"user_id"`
	VocabularyID int64     `db:"vocabulary_id"`
	ImageURL     string    `db:"image_url"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

// FlashcardSentence is a sentence confirmed onto a flashcard — either typed
// by the user directly, or picked from the AI suggestions.
type FlashcardSentence struct {
	ID           int64     `db:"id"`
	FlashcardID  string    `db:"flashcard_id"`
	SentenceText string    `db:"sentence_text"`
	Source       string    `db:"source"` // "user" or "ai_picked"
	CreatedAt    time.Time `db:"created_at"`
}

// AISuggestedSentence is a candidate sentence generated by AI for a
// flashcard, shown to the user to either pick (-> FlashcardSentence) or ignore.
type AISuggestedSentence struct {
	ID           int64     `db:"id"`
	FlashcardID  string    `db:"flashcard_id"`
	SentenceText string    `db:"sentence_text"`
	CreatedAt    time.Time `db:"created_at"`
}
